import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import { cn } from "@/lib/utils/utils";
import "@/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn("bg-white text-slate-900 antialiased", inter.className)}
    >
      <body
        className={cn("min-h-screen bg-slate-50 dark:bg-slate-900 antialiased")}
      >
        {/* @ts-expect-error Server Components */}
        <Navbar />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
